### PR TITLE
feat(markdown): support codespell

### PR DESCRIPTION
**Pull request by hougesen**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm unsure what it's supposed to achieve.

I know codespell very well.

It might suggest multiple solutions to fix a typo. So -w won't fix it. You will have to fix it manually, and typos will return an non-zero exist code, which may be interpreted wrongly by your tool

You might have to use  `-i` from 0 to 3, but this parameter is about being interactive.

**Comment by hougesen** [comment]
Adding support for spellcheckers seemed like a nobrainer since this tool is focused on documentation already. You are right that it shouldn't autofix in case of wrong suggestions.

**Comment by ccoVeille** [comment]
> Adding support for spellcheckers seemed like a nobrainer since this tool is focused on documentation already. You are right that it shouldn't autofix in case of wrong suggestions. 
> 

My point was also about your code should catch the errors code and report the errors or a message.

But I agree it's a great addition

**Comment by ccoVeille** [comment]
Let's continue the discussion here.

I'm unsure why you rolled back typos fixing with #237 and #236 ?

**Comment by hougesen** [comment]
I must have misunderstood what you meant by

> It might suggest multiple solutions to fix a typo. So -w won't fix it. You will have to fix it manually, and it will return an non-zero exist code, which may be interpreted wrongly by your tool

**Comment by ccoVeille** [comment]
My point was that codespell and typos could recommend multiple words for the same typo

Like for "thn", they might suggest 
- the
- than
- then

I saw you rolled back, so it's great.

My concern was the fact than when they are alternative that cannot be fixed. typos or codespell will return a non-zero code, so you will receive it as if the tool was in error.

So you might be aware of it and handle these use cases by reporting these warnings.

**Pull request merged**
